import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Footer from "./Footer";
import React, { Suspense } from "react";
import { Analytics } from "@vercel/analytics/next";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Electronics Store",
  description: "Generated by create next app",
};

const RootLayout= async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className="min-h-screen flex flex-col">

    <Suspense fallback={null}>
      <Navbar />
    <Sidebar />
    <main className="grow pt-16">{children}</main>
    <Footer />
    </Suspense>
    <Analytics />
</body>
    </html>
  );
}

export default React.memo(RootLayout);